from app.schemas import ApprovalCaseInput, ChargeItem, PartnerFeeInput


SAMPLE_CASES: dict[str, ApprovalCaseInput] = {
    "TOWA_SI_PLUS_PLUS": ApprovalCaseInput(
        customer_name="TOWA CO., LTD.",
        trade_type="SHIPPER",
        mode="SEA",
        direction="IMPORT",
        has_customs=True,
        has_transport=True,
        pol="BUSAN",
        pod="TOKYO",
        port="TOKYO",
        container_type="20DC",
        container_count=1,
        revenue_items=[
            ChargeItem(name="TOTAL", amount_jpy=468146),
            ChargeItem(name="CUSTOMS", amount_jpy=0),
        ],
        expense_items=[ChargeItem(name="TOTAL", amount_jpy=443653)],
        customs_duty_jpy=0,
        consumption_tax_jpy=300300,
        transport_revenue_jpy=61000,
        transport_expense_jpy=60000,
        customs_revenue_jpy=11800,
        customs_expense_jpy=0,
        self_customs=True,
        pic="K.J.KIM",
    ),
    "KANGKOKU_HIROBA_SI_PLUS_PLUS": ApprovalCaseInput(
        customer_name="KANGKOKU HIROBA",
        trade_type="SHIPPER",
        mode="SEA",
        direction="IMPORT",
        has_customs=True,
        has_transport=True,
        pol="BUSAN",
        pod="TOKYO",
        port="TOKYO",
        cargo_description="Frozen Abalone",
        container_type="20RF",
        container_count=1,
        revenue_items=[
            ChargeItem(name="TOTAL", amount_jpy=2640238),
            ChargeItem(name="CUSTOMS", amount_jpy=0),
            ChargeItem(name="FOOD", amount_jpy=0),
        ],
        expense_items=[ChargeItem(name="TOTAL", amount_jpy=2495061)],
        customs_duty_jpy=1131700,
        consumption_tax_jpy=1071200,
        transport_revenue_jpy=78000,
        transport_expense_jpy=65000,
        customs_revenue_jpy=11800,
        customs_expense_jpy=0,
        self_customs=True,
        pic="K.J.KIM",
    ),
    "HUMAN_MADE_SE_PLUS_PLUS": ApprovalCaseInput(
        customer_name="HUMAN MADE INC.",
        trade_type="PARTNER",
        partner_name="SOLTRANS CO., LTD",
        mode="SEA",
        direction="EXPORT",
        has_customs=True,
        has_transport=True,
        pol="YOKOHAMA",
        pod="BUSAN",
        port="YOKOHAMA",
        container_type="LCL",
        revenue_items=[
            ChargeItem(name="TOTAL", amount_jpy=120510),
            ChargeItem(name="CUSTOMS", amount_jpy=0),
        ],
        expense_items=[ChargeItem(name="TOTAL", amount_jpy=87710)],
        transport_revenue_jpy=31000,
        transport_expense_jpy=25000,
        customs_revenue_jpy=11800,
        customs_expense_jpy=0,
        self_customs=True,
        pic="J.W.PARK",
    ),
    "PNS_SE": ApprovalCaseInput(
        customer_name="SUMITOMO CHEMICAL",
        trade_type="PARTNER",
        partner_name="PNS NETWORKS CO., LTD",
        mode="SEA",
        direction="EXPORT",
        has_customs=False,
        has_transport=False,
        pol="KOBE",
        pod="BUSAN",
        port="KOBE",
        container_type="40HC",
        container_count=2,
        revenue_items=[ChargeItem(name="TOTAL", amount_jpy=144798)],
        expense_items=[ChargeItem(name="TOTAL", amount_jpy=124000)],
        partner_fee=PartnerFeeInput(
            partner_name="PNS NETWORKS CO., LTD",
            actual_fee_usd=30,
            container_type="40HC",
            container_count=2,
        ),
        pic="J.W.PARK",
    ),
    "PNS_SE_FEE_MISSING": ApprovalCaseInput(
        customer_name="SUMITOMO CHEMICAL",
        trade_type="PARTNER",
        partner_name="PNS NETWORKS CO., LTD",
        mode="SEA",
        direction="EXPORT",
        has_customs=False,
        has_transport=False,
        pol="KOBE",
        pod="BUSAN",
        port="KOBE",
        container_type="40HC",
        container_count=2,
        revenue_items=[ChargeItem(name="TOTAL", amount_jpy=144798)],
        expense_items=[ChargeItem(name="TOTAL", amount_jpy=124000)],
        partner_fee=PartnerFeeInput(
            partner_name="PNS NETWORKS CO., LTD",
            actual_fee_usd=0,
            container_type="40HC",
            container_count=2,
        ),
        pic="J.W.PARK",
    ),
    "DONGSHIN_SI": ApprovalCaseInput(
        customer_name="STAR WORLD",
        trade_type="PARTNER",
        partner_name="DONGSHIN SEA & AIR",
        mode="SEA",
        direction="IMPORT",
        has_customs=False,
        has_transport=False,
        pol="BUSAN",
        pod="OSAKA",
        port="OSAKA",
        container_type="LCL",
        revenue_items=[ChargeItem(name="TOTAL", amount_jpy=50267)],
        expense_items=[ChargeItem(name="TOTAL", amount_jpy=39139)],
        partner_fee=PartnerFeeInput(
            partner_name="DONGSHIN SEA & AIR",
            actual_fee_jpy=4000,
        ),
        pic="UTSUGI",
    ),
}
